---
title: "The Stockholm Public Health Cohort (SPHC) 2014, followed up to 2021"
author: Willi Zhang, Maya Mathur
email: willi.zhang@ki.se
output: html_notebook
editor_options: 
  chunk_output_type: console
---

### 1. Load Packages
```{r}
library(tidyverse)
library(naniar)
library(haven)
library(finalfit)
library(mice)
```

### 2. SPHC 2014
```{r}
load('/Volumes/LGBT Project data/d_2014.RData')

# sexual identity in 2014
table( d_2014$F14U90G82, useNA = "always" )
d_2014$sexual_identity_2014 <- factor( ifelse( d_2014$F14U90G82 == 1, "Heterosexual", "Non-heterosexual" ),
                                       levels = c( "Heterosexual", "Non-heterosexual" ) )
table( d_2014$sexual_identity_2014, useNA = "always" )

# sexual identity in 2021
table( d_2014$F21F91, useNA = "always" )
d_2014$sexual_identity_2021 <- factor( ifelse( d_2014$F21F91 == 1, "Heterosexual", "Non-heterosexual" ),
                                       levels = c( "Heterosexual", "Non-heterosexual" ) )
table( d_2014$sexual_identity_2021, useNA = "always" )

# change in sexual identity
d_2014$identity_change <- ifelse( d_2014$sexual_identity_2014 == d_2014$sexual_identity_2021, 0, 1 )
table( d_2014$identity_change, useNA = "always" )

# age
summary( d_2014$F14alder )
d_2014$age_2014 <- d_2014$F14alder

# sex
table( d_2014$kon, useNA = "always" )
d_2014$sex <- factor( ifelse( d_2014$kon == 1, "Male", "Female" ),
                      levels = c( "Male", "Female" ) )
table( d_2014$sex, useNA = "always" )

# country of birth
table( d_2014$fodelseland, useNA = "always" )
d_2014$country_of_birth <- factor( ifelse( d_2014$fodelseland == "Sverige", "Sweden",
                                           ifelse( d_2014$fodelseland == "Europa", "Europe", "Outside Europe" ) ),
                                   levels = c( "Sweden", "Europe", "Outside Europe" ) )
table( d_2014$country_of_birth, useNA = "always" )

# disposable income
summary( d_2014$dispink2014, useNA = "always" )
d_2014$dispink2014[ d_2014$dispink2014 < 0 ] <- NA
d_2014$dispink2014 <- d_2014$dispink2014*( 415.15/313.49 ) # Consumer Price Index (CPI)-adjusted income using the year 2024 as the reference (https://www.statistikdatabasen.scb.se/pxweb/en/ssd/START__PR__PR0101__PR0101L/KPIFastAmed/table/tableViewLayout1/)
d_2014$income_2014 <- factor( ifelse( d_2014$dispink2014 <= 2500, "<=2,500",
                                      ifelse( d_2014$dispink2014 > 2500 & d_2014$dispink2014 <= 3500, "(2,500, 3,500]",
                                              ifelse( d_2014$dispink2014 > 3500 & d_2014$dispink2014 <= 4500, "(3,500, 4,500]", ">4,500" ) ) ),
                              levels = c( "<=2,500", "(2,500, 3,500]", "(3,500, 4,500]", ">4,500" ),
                              ordered = TRUE )
table( d_2014$income_2014, useNA = "always" )

# use of antidepressants and anxiolytics
atc_2002_2014 <- read_sas('/Volumes/LGBT Project data/Swedish Registers/atc_pdr_2002_2014.sas7bdat') %>%
  filter( !grepl( "^N05CD", ATC ) ) # include participants who had at least one dispensed prescription of N06A (antidepressants) or N05B (anxiolytics) from 2005-06-30 to 2021-12-31

# check variables
unique( atc_2002_2014$ATC )
summary( atc_2002_2014$EDATUM )
length( intersect( atc_2002_2014$lopnr, d_2014$lopnr ) ) # 8,419 in SPHC 2014

atc_2014 <- atc_2002_2014 %>%
  filter( lopnr %in% d_2014$lopnr ) %>% # select SPHC 2014 participants
  select( lopnr, ATC, EDATUM ) %>%
  rename( dispense_date = EDATUM ) %>%
  filter( dispense_date >= as.Date( "2014-08-31" ) & dispense_date <= as.Date( "2015-02-28" ) ) # select prescription data for half a year (2014-08-31 was the date when sampling frame was selected from the Total Population Register)

summary( atc_2014$dispense_date )

antidepressant_users <- atc_2014 %>%
  filter( startsWith( ATC, "N06A" ) ) %>%
  pull( lopnr ) %>%
  unique()

anxiolytic_users <- atc_2014 %>%
  filter( startsWith( ATC, "N05B" ) ) %>%
  pull( lopnr ) %>%
  unique()

d_2014 <- d_2014 %>%
  mutate(
    antidepressant_use_2014 = as.factor( if_else( lopnr %in% antidepressant_users, "Yes", "No" ) ),
    anxiolytic_use_2014 = as.factor( if_else( lopnr %in% anxiolytic_users, "Yes", "No" ) )
    )

summary( d_2014$antidepressant_use_2014 )
summary( d_2014$anxiolytic_use_2014 )

d_2014_prelim <- d_2014 %>% 
  select( "sexual_identity_2014", "sexual_identity_2021", "identity_change", "age_2014", "sex", "country_of_birth", "income_2014", "antidepressant_use_2014", "anxiolytic_use_2014" )
summary( d_2014_prelim )
miss_var_summary( d_2014_prelim ) # 41.2% missing in identity_change, 37.6% in sexual_identity_2021, 9.0% in sexual_identity_2014, 0.2% in income_2014

# among participants in 2021 (N = 14,704), 819 (5.6%) did not report sexual identity. Therefore, the missingness in sexual_identity_2021 was primarily due to loss to follow-up

# select a subgroup
d_2014_selected <- d_2014_prelim %>%
  filter( age_2014 >= 25 & age_2014 <= 45 ) # select participants aged 25-45 at baseline, because this age group, relative to younger individuals, would be relatively stable socioeconomically
summary( d_2014_selected )
nrow( d_2014_selected ) # 6,685
miss_var_summary( d_2014_selected ) # 42.3% missing in identity_change, 38.2% in sexual_identity_2021, 10.4% in sexual_identity_2014, 0.2% in income_2014

# characteristics table
explanatory =  c( "sexual_identity_2021", "sex", "age_2014", "country_of_birth", "income_2014", "antidepressant_use_2014", "anxiolytic_use_2014" )
dependent = "sexual_identity_2014"

d_2014_table <- d_2014_selected %>%
  mutate( antidepressant_use_2014 = fct_rev( antidepressant_use_2014 ),
          anxiolytic_use_2014 = fct_rev( anxiolytic_use_2014 ) ) %>%
  summary_factorlist( dependent,
                      explanatory, 
                      na_include = TRUE,
                      na_include_dependent = TRUE, 
                      total_col = TRUE,
                      add_col_totals = TRUE,
                      column = TRUE )


# correlation of sexual identities in 2014 and 2021
ggplot( d_2014_selected %>% filter( !is.na( sexual_identity_2014 ) & !is.na( sexual_identity_2021 ) ),
        aes( x = sexual_identity_2014, fill = sexual_identity_2021 ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Sexual Identity in 2014", y = "Percentage", fill = "Sexual Identity in 2021" ) +
  theme_classic()

tab <- table( d_2014_selected$sexual_identity_2014, d_2014_selected$sexual_identity_2021 )
tab
( tab[ "Non-heterosexual", "Non-heterosexual" ] / sum( tab[ "Non-heterosexual", ] ) ) / 
  ( tab[ "Heterosexual", "Non-heterosexual" ] / sum( tab[ "Heterosexual", ] ) ) # RR = 21.7


# correlation of sexual identity in 2014 and missingness of sexual identity in 2021
ggplot( d_2014_selected %>% filter( !is.na( sexual_identity_2014 ) ),
        aes( x = sexual_identity_2014, fill = is.na( sexual_identity_2021 ) ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Sexual Identity in 2014", y = "Percentage", fill = "Missingness of Sexual Identity in 2021" ) +
  theme_classic()

tab <- table( d_2014_selected$sexual_identity_2014, is.na( d_2014_selected$sexual_identity_2021 ) )
tab
( tab[ "Non-heterosexual", "TRUE" ] / sum( tab[ "Non-heterosexual", ] ) ) / 
  ( tab[ "Heterosexual", "TRUE" ] / sum( tab[ "Heterosexual", ] ) ) # RR = 1.32


# correlation of sexual identity in 2014 and income
ggplot( d_2014_selected %>% filter( !is.na( sexual_identity_2014 ) & !is.na( income_2014 ) ),
        aes( x = income_2014, fill = sexual_identity_2014 ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Income (100 SEK/Year)", y = "Percentage", fill = "Sexual Identity in 2014" ) +
  theme_classic()


# correlation of income and sexual identity in 2021
ggplot( d_2014_selected %>% filter( !is.na( sexual_identity_2021 ) & !is.na( income_2014 ) ),
        aes( x = income_2014, fill = sexual_identity_2021 ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Income (100 SEK/Year)", y = "Percentage", fill = "Sexual Identity in 2021" ) +
  theme_classic()


# correlation of income and missingness of sexual identity in 2021
ggplot( d_2014_selected %>% filter( !is.na( income_2014 ) ),
       aes( x = income_2014, fill = is.na( sexual_identity_2021 ) ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Income (100 SEK/Year)", y = "Percentage", fill = "Missingness of Sexual Identity in 2021" ) +
  theme_classic()


# correlation of mental health and income
ggplot( d_2014_selected %>% filter( !is.na( income_2014 ) ),
       aes( x = income_2014, fill = antidepressant_use_2014 ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Income (100 SEK/Year)", y = "Percentage", fill = "Antidepressant Use" ) +
  theme_classic()

ggplot( d_2014_selected %>% filter( !is.na( income_2014 ) ),
       aes( x = income_2014, fill = anxiolytic_use_2014 ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Income (100 SEK/Year)", y = "Percentage", fill = "Anxiolytic Use" ) +
  theme_classic()


# correlation of mental health and missingness of sexual identity in 2021
ggplot( d_2014_selected,
        aes( x = antidepressant_use_2014, fill = is.na( sexual_identity_2021 ) ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Antidepressant Use", y = "Percentage", fill = "Missingness of Sexual Identity in 2021" ) +
  theme_classic()

tab <- table( d_2014_selected$antidepressant_use_2014, is.na( d_2014_selected$sexual_identity_2021 ) )
tab
( tab[ "Yes", "TRUE" ] / sum( tab[ "Yes", ] ) ) / 
  ( tab[ "No", "TRUE" ] / sum( tab[ "No", ] ) ) # RR = 1.13

ggplot( d_2014_selected,
        aes( x = anxiolytic_use_2014, fill = is.na( sexual_identity_2021 ) ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Anxiolytic Use", y = "Percentage", fill = "Missingness of Sexual Identity in 2021" ) +
  theme_classic()

tab <- table( d_2014_selected$anxiolytic_use_2014, is.na( d_2014_selected$sexual_identity_2021 ) )
tab
( tab[ "Yes", "TRUE" ] / sum( tab[ "Yes", ] ) ) / 
  ( tab[ "No", "TRUE" ] / sum( tab[ "No", ] ) ) # RR = 1.12


# correlation of sexual identity in 2014 and mental health
ggplot( d_2014_selected %>% filter( !is.na( sexual_identity_2014 ) ),
        aes( x = sexual_identity_2014, fill = antidepressant_use_2014 ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Sexual Identity in 2014", y = "Percentage", fill = "Antidepressant Use" ) +
  theme_classic()

tab <- table( d_2014_selected$sexual_identity_2014, d_2014_selected$antidepressant_use_2014 )
tab
( tab[ "Non-heterosexual", "Yes" ] / sum( tab[ "Non-heterosexual", ] ) ) / 
  ( tab[ "Heterosexual", "Yes" ] / sum( tab[ "Heterosexual", ] ) ) # RR = 1.77

ggplot( d_2014_selected %>% filter( !is.na( sexual_identity_2014 ) ),
        aes( x = sexual_identity_2014, fill = anxiolytic_use_2014 ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Sexual Identity in 2014", y = "Percentage", fill = "Anxiolytic Use" ) +
  theme_classic()

tab <- table( d_2014_selected$sexual_identity_2014, d_2014_selected$anxiolytic_use_2014 )
tab
( tab[ "Non-heterosexual", "Yes" ] / sum( tab[ "Non-heterosexual", ] ) ) / 
  ( tab[ "Heterosexual", "Yes" ] / sum( tab[ "Heterosexual", ] ) ) # RR = 2.07
```

### 3. Among Females
```{r}
# select a subgroup
d_2014_selected_female <- d_2014_selected %>%
  filter( sex == "Female" ) # select female participants aged 25-45 at baseline
summary( d_2014_selected_female )
nrow( d_2014_selected_female )
miss_var_summary( d_2014_selected_female )
```

#### 3.1. Complete-case analysis
```{r}
d_cc <- d_2014_selected_female %>% filter( !is.na( identity_change )  )
nrow( d_cc )
summary( d_cc )

model_cc <- glm( identity_change ~ sexual_identity_2014, 
                 family = binomial( link = "log" ), 
                 data = d_cc )

tidy_cc <- tidy( model_cc, conf.int = TRUE, conf.level = 0.95 )
tidy_cc

model_cc <- tibble(
  "Estimate (log RR)" = round( tidy_cc[[ 2, "estimate" ]], 3 ), 
  "SE" = round( tidy_cc[[ 2, "std.error" ]], 3 ),
  "Lower CI" = round( tidy_cc[[ 2, "conf.low" ]], 3 ),
  "Upper CI" = round( tidy_cc[[ 2, "conf.high" ]], 3 ),
  
  "RR [95% CI]" = paste0(
    round( exp( tidy_cc[[ 2, "estimate" ]] ), 2 ), " [",
    round( exp( tidy_cc[[ 2, "conf.low" ]] ), 2 ), ", ",
    round( exp( tidy_cc[[ 2, "conf.high" ]] ), 2 ), "]" )
)

model_cc[["Imputation Model"]] <- "Complete-case analysis"
model_cc
```

#### 3.2. Imputation models
##### 3.2.1. Model 1
```{r}
# only include sexual identity

impute_data_1 <- d_2014_selected_female %>%
  select( sexual_identity_2014, sexual_identity_2021 )
summary( impute_data_1 )
str( impute_data_1 )
miss_var_summary( impute_data_1  )

imp_1 <- mice( impute_data_1, m = 50, seed = 123, print = FALSE )
summary( imp_1 )
plot( imp_1 )

long_data_1 <- complete( imp_1, action = "long", include = TRUE )
long_data_1$identity_change <- ifelse( long_data_1$sexual_identity_2014 == long_data_1$sexual_identity_2021, 0, 1 )
summary( long_data_1 )

fit_model_1 <- with( as.mids( long_data_1 ),
                     glm( identity_change ~ sexual_identity_2014, family = binomial( link = "log" ) ) )

pooled_summary_1 <- summary( pool( fit_model_1 ), conf.int = TRUE )
pooled_summary_1

model_1 <- tibble(
  "Estimate (log RR)" = round( pooled_summary_1[[ 2, "estimate" ]], 3 ), 
  "SE" = round( pooled_summary_1[[ 2, "std.error" ]], 3 ),
  "Lower CI" = round( pooled_summary_1[[ 2, "conf.low" ]], 3 ),
  "Upper CI" = round( pooled_summary_1[[ 2, "conf.high" ]], 3 ),
  
  "RR [95% CI]" = paste0(
    round( exp( pooled_summary_1[[ 2, "estimate" ]] ), 2 ), " [",
    round( exp( pooled_summary_1[[ 2, "conf.low" ]] ), 2 ), ", ",
    round( exp( pooled_summary_1[[ 2, "conf.high" ]] ), 2 ), "]" )
)
model_1[["Imputation Model"]] <- "Model 1: sexual identity"
model_1
```

##### 3.2.2. Model 2
```{r}
# additionally include age and country of birth

impute_data_2 <- d_2014_selected_female %>%
  select( sexual_identity_2014, sexual_identity_2021, age_2014, country_of_birth )
summary( impute_data_2 )
str( impute_data_2 )
miss_var_summary( impute_data_2  )

imp_2 <- mice( impute_data_2, m = 50, seed = 123, print = FALSE )
summary( imp_2 )
plot( imp_2 )

long_data_2 <- complete( imp_2, action = "long", include = TRUE )
long_data_2$identity_change <- ifelse( long_data_2$sexual_identity_2014 == long_data_2$sexual_identity_2021, 0, 1 )
summary( long_data_2 )

fit_model_2 <- with( as.mids( long_data_2 ),
                     glm( identity_change ~ sexual_identity_2014, family = binomial( link = "log" ) ) )

pooled_summary_2 <- summary( pool( fit_model_2 ), conf.int = TRUE )
pooled_summary_2

model_2 <- tibble(
  "Estimate (log RR)" = round( pooled_summary_2[[ 2, "estimate" ]], 3 ), 
  "SE" = round( pooled_summary_2[[ 2, "std.error" ]], 3 ),
  "Lower CI" = round( pooled_summary_2[[ 2, "conf.low" ]], 3 ),
  "Upper CI" = round( pooled_summary_2[[ 2, "conf.high" ]], 3 ),
  
  "RR [95% CI]" = paste0(
    round( exp( pooled_summary_2[[ 2, "estimate" ]] ), 2 ), " [",
    round( exp( pooled_summary_2[[ 2, "conf.low" ]] ), 2 ), ", ",
    round( exp( pooled_summary_2[[ 2, "conf.high" ]] ), 2 ), "]" )
)
model_2[["Imputation Model"]] <- "Model 2: sexual identity, age, country of birth"
model_2
```

##### 3.2.3. Model 3
```{r}
# additionally include age, country of birth, and income

impute_data_3 <- d_2014_selected_female %>%
  select( sexual_identity_2014, sexual_identity_2021, age_2014, country_of_birth, income_2014 )
summary( impute_data_3 )
str( impute_data_3 )
miss_var_summary( impute_data_3  )

imp_3 <- mice( impute_data_3, m = 50, seed = 123, print = FALSE )
summary( imp_3 )
plot( imp_3 )

long_data_3 <- complete( imp_3, action = "long", include = TRUE )
long_data_3$identity_change <- ifelse( long_data_3$sexual_identity_2014 == long_data_3$sexual_identity_2021, 0, 1 )
summary( long_data_3 )

fit_model_3 <- with( as.mids( long_data_3 ),
                     glm( identity_change ~ sexual_identity_2014, family = binomial( link = "log" ) ) )

pooled_summary_3 <- summary( pool( fit_model_3 ), conf.int = TRUE )
pooled_summary_3

model_3 <- tibble(
  "Estimate (log RR)" = round( pooled_summary_3[[ 2, "estimate" ]], 3 ), 
  "SE" = round( pooled_summary_3[[ 2, "std.error" ]], 3 ),
  "Lower CI" = round( pooled_summary_3[[ 2, "conf.low" ]], 3 ),
  "Upper CI" = round( pooled_summary_3[[ 2, "conf.high" ]], 3 ),
  
  "RR [95% CI]" = paste0(
    round( exp( pooled_summary_3[[ 2, "estimate" ]] ), 2 ), " [",
    round( exp( pooled_summary_3[[ 2, "conf.low" ]] ), 2 ), ", ",
    round( exp( pooled_summary_3[[ 2, "conf.high" ]] ), 2 ), "]" )
)
model_3[["Imputation Model"]] <- "Model 3: sexual identity, age, country of birth, income"
model_3
```

##### 3.2.4. Model 4
```{r}
# additionally include age, country of birth, antidepressant use, and anxiolytic use

impute_data_4 <- d_2014_selected_female %>%
  select( sexual_identity_2014, sexual_identity_2021, age_2014, country_of_birth, antidepressant_use_2014, anxiolytic_use_2014 )
summary( impute_data_4 )
str( impute_data_4 )
miss_var_summary( impute_data_4  )

imp_4 <- mice( impute_data_4, m = 50, seed = 123, print = FALSE )
summary( imp_4 )
plot( imp_4 )

long_data_4 <- complete( imp_4, action = "long", include = TRUE )
long_data_4$identity_change <- ifelse( long_data_4$sexual_identity_2014 == long_data_4$sexual_identity_2021, 0, 1 )
summary( long_data_4 )

fit_model_4 <- with( as.mids( long_data_4 ),
                     glm( identity_change ~ sexual_identity_2014, family = binomial( link = "log" ) ) )

pooled_summary_4 <- summary( pool( fit_model_4 ), conf.int = TRUE )
pooled_summary_4

model_4 <- tibble(
  "Estimate (log RR)" = round( pooled_summary_4[[ 2, "estimate" ]], 3 ), 
  "SE" = round( pooled_summary_4[[ 2, "std.error" ]], 3 ),
  "Lower CI" = round( pooled_summary_4[[ 2, "conf.low" ]], 3 ),
  "Upper CI" = round( pooled_summary_4[[ 2, "conf.high" ]], 3 ),
  
  "RR [95% CI]" = paste0(
    round( exp( pooled_summary_4[[ 2, "estimate" ]] ), 2 ), " [",
    round( exp( pooled_summary_4[[ 2, "conf.low" ]] ), 2 ), ", ",
    round( exp( pooled_summary_4[[ 2, "conf.high" ]] ), 2 ), "]" )
)
model_4[["Imputation Model"]] <- "Model 4: sexual identity, age, country of birth, antidepressant use, anxiolytic use"
model_4
```

##### 3.2.5. Model 5
```{r}
# additionally include age, country of birth, income, antidepressant use, and anxiolytic use

impute_data_5 <- d_2014_selected_female %>%
  select( sexual_identity_2014, sexual_identity_2021, age_2014, country_of_birth, income_2014, antidepressant_use_2014, anxiolytic_use_2014 )
summary( impute_data_5 )
str( impute_data_5 )
miss_var_summary( impute_data_5  )

imp_5 <- mice( impute_data_5, m = 50, seed = 123, print = FALSE )
summary( imp_5 )
plot( imp_5 )

long_data_5 <- complete( imp_5, action = "long", include = TRUE )
long_data_5$identity_change <- ifelse( long_data_5$sexual_identity_2014 == long_data_5$sexual_identity_2021, 0, 1 )
summary( long_data_5 )

fit_model_5 <- with( as.mids( long_data_5 ),
                     glm( identity_change ~ sexual_identity_2014, family = binomial( link = "log" ) ) )

pooled_summary_5 <- summary( pool( fit_model_5 ), conf.int = TRUE )
pooled_summary_5

model_5 <- tibble(
  "Estimate (log RR)" = round( pooled_summary_5[[ 2, "estimate" ]], 3 ), 
  "SE" = round( pooled_summary_5[[ 2, "std.error" ]], 3 ),
  "Lower CI" = round( pooled_summary_5[[ 2, "conf.low" ]], 3 ),
  "Upper CI" = round( pooled_summary_5[[ 2, "conf.high" ]], 3 ),
  
  "RR [95% CI]" = paste0(
    round( exp( pooled_summary_5[[ 2, "estimate" ]] ), 2 ), " [",
    round( exp( pooled_summary_5[[ 2, "conf.low" ]] ), 2 ), ", ",
    round( exp( pooled_summary_5[[ 2, "conf.high" ]] ), 2 ), "]" )
)
model_5[["Imputation Model"]] <- "Model 5: sexual identity, age, country of birth, income, antidepressant use, anxiolytic use"
model_5
```

##### 3.2.6. Print results
```{r}
bind_rows(
  model_cc, model_1, model_2, model_3, model_4, model_5
)
```

### 4. Among Males
```{r}
# select a subgroup
d_2014_selected_male <- d_2014_selected %>%
  filter( sex == "Male" ) # select male participants aged 25-45 at baseline
summary( d_2014_selected_male )
nrow( d_2014_selected_male )
miss_var_summary( d_2014_selected_male )
```

#### 4.1. Complete-case analysis
```{r}
d_cc <- d_2014_selected_male %>% filter( !is.na( identity_change )  )
nrow( d_cc )
summary( d_cc )

model_cc <- glm( identity_change ~ sexual_identity_2014, 
                 family = binomial( link = "log" ), 
                 data = d_cc )

tidy_cc <- tidy( model_cc, conf.int = TRUE, conf.level = 0.95 )
tidy_cc

model_cc <- tibble(
  "Estimate (log RR)" = round( tidy_cc[[ 2, "estimate" ]], 3 ), 
  "SE" = round( tidy_cc[[ 2, "std.error" ]], 3 ),
  "Lower CI" = round( tidy_cc[[ 2, "conf.low" ]], 3 ),
  "Upper CI" = round( tidy_cc[[ 2, "conf.high" ]], 3 ),
  
  "RR [95% CI]" = paste0(
    round( exp( tidy_cc[[ 2, "estimate" ]] ), 2 ), " [",
    round( exp( tidy_cc[[ 2, "conf.low" ]] ), 2 ), ", ",
    round( exp( tidy_cc[[ 2, "conf.high" ]] ), 2 ), "]" )
)

model_cc[["Imputation Model"]] <- "Complete-case analysis"
model_cc
```

#### 4.2. Imputation models
##### 4.2.1. Model 1
```{r}
# only include sexual identity

impute_data_1 <- d_2014_selected_male %>%
  select( sexual_identity_2014, sexual_identity_2021 )
summary( impute_data_1 )
str( impute_data_1 )
miss_var_summary( impute_data_1  )

imp_1 <- mice( impute_data_1, m = 50, seed = 123, print = FALSE )
summary( imp_1 )
plot( imp_1 )

long_data_1 <- complete( imp_1, action = "long", include = TRUE )
long_data_1$identity_change <- ifelse( long_data_1$sexual_identity_2014 == long_data_1$sexual_identity_2021, 0, 1 )
summary( long_data_1 )

fit_model_1 <- with( as.mids( long_data_1 ),
                     glm( identity_change ~ sexual_identity_2014, family = binomial( link = "log" ) ) )

pooled_summary_1 <- summary( pool( fit_model_1 ), conf.int = TRUE )
pooled_summary_1

model_1 <- tibble(
  "Estimate (log RR)" = round( pooled_summary_1[[ 2, "estimate" ]], 3 ), 
  "SE" = round( pooled_summary_1[[ 2, "std.error" ]], 3 ),
  "Lower CI" = round( pooled_summary_1[[ 2, "conf.low" ]], 3 ),
  "Upper CI" = round( pooled_summary_1[[ 2, "conf.high" ]], 3 ),
  
  "RR [95% CI]" = paste0(
    round( exp( pooled_summary_1[[ 2, "estimate" ]] ), 2 ), " [",
    round( exp( pooled_summary_1[[ 2, "conf.low" ]] ), 2 ), ", ",
    round( exp( pooled_summary_1[[ 2, "conf.high" ]] ), 2 ), "]" )
)
model_1[["Imputation Model"]] <- "Model 1: sexual identity"
model_1
```

##### 4.2.2. Model 2
```{r}
# additionally include age and country of birth

impute_data_2 <- d_2014_selected_male %>%
  select( sexual_identity_2014, sexual_identity_2021, age_2014, country_of_birth )
summary( impute_data_2 )
str( impute_data_2 )
miss_var_summary( impute_data_2  )

imp_2 <- mice( impute_data_2, m = 50, seed = 123, print = FALSE )
summary( imp_2 )
plot( imp_2 )

long_data_2 <- complete( imp_2, action = "long", include = TRUE )
long_data_2$identity_change <- ifelse( long_data_2$sexual_identity_2014 == long_data_2$sexual_identity_2021, 0, 1 )
summary( long_data_2 )

fit_model_2 <- with( as.mids( long_data_2 ),
                     glm( identity_change ~ sexual_identity_2014, family = binomial( link = "log" ) ) )

pooled_summary_2 <- summary( pool( fit_model_2 ), conf.int = TRUE )
pooled_summary_2

model_2 <- tibble(
  "Estimate (log RR)" = round( pooled_summary_2[[ 2, "estimate" ]], 3 ), 
  "SE" = round( pooled_summary_2[[ 2, "std.error" ]], 3 ),
  "Lower CI" = round( pooled_summary_2[[ 2, "conf.low" ]], 3 ),
  "Upper CI" = round( pooled_summary_2[[ 2, "conf.high" ]], 3 ),
  
  "RR [95% CI]" = paste0(
    round( exp( pooled_summary_2[[ 2, "estimate" ]] ), 2 ), " [",
    round( exp( pooled_summary_2[[ 2, "conf.low" ]] ), 2 ), ", ",
    round( exp( pooled_summary_2[[ 2, "conf.high" ]] ), 2 ), "]" )
)
model_2[["Imputation Model"]] <- "Model 2: sexual identity, age, country of birth"
model_2
```

##### 4.2.3. Model 3
```{r}
# additionally include age, country of birth, and income

impute_data_3 <- d_2014_selected_male %>%
  select( sexual_identity_2014, sexual_identity_2021, age_2014, country_of_birth, income_2014 )
summary( impute_data_3 )
str( impute_data_3 )
miss_var_summary( impute_data_3  )

imp_3 <- mice( impute_data_3, m = 50, seed = 123, print = FALSE )
summary( imp_3 )
plot( imp_3 )

long_data_3 <- complete( imp_3, action = "long", include = TRUE )
long_data_3$identity_change <- ifelse( long_data_3$sexual_identity_2014 == long_data_3$sexual_identity_2021, 0, 1 )
summary( long_data_3 )

fit_model_3 <- with( as.mids( long_data_3 ),
                     glm( identity_change ~ sexual_identity_2014, family = binomial( link = "log" ) ) )

pooled_summary_3 <- summary( pool( fit_model_3 ), conf.int = TRUE )
pooled_summary_3

model_3 <- tibble(
  "Estimate (log RR)" = round( pooled_summary_3[[ 2, "estimate" ]], 3 ), 
  "SE" = round( pooled_summary_3[[ 2, "std.error" ]], 3 ),
  "Lower CI" = round( pooled_summary_3[[ 2, "conf.low" ]], 3 ),
  "Upper CI" = round( pooled_summary_3[[ 2, "conf.high" ]], 3 ),
  
  "RR [95% CI]" = paste0(
    round( exp( pooled_summary_3[[ 2, "estimate" ]] ), 2 ), " [",
    round( exp( pooled_summary_3[[ 2, "conf.low" ]] ), 2 ), ", ",
    round( exp( pooled_summary_3[[ 2, "conf.high" ]] ), 2 ), "]" )
)
model_3[["Imputation Model"]] <- "Model 3: sexual identity, age, country of birth, income"
model_3
```

##### 4.2.4. Model 4
```{r}
# additionally include age, country of birth, antidepressant use, and anxiolytic use

impute_data_4 <- d_2014_selected_male %>%
  select( sexual_identity_2014, sexual_identity_2021, age_2014, country_of_birth, antidepressant_use_2014, anxiolytic_use_2014 )
summary( impute_data_4 )
str( impute_data_4 )
miss_var_summary( impute_data_4  )

imp_4 <- mice( impute_data_4, m = 50, seed = 123, print = FALSE )
summary( imp_4 )
plot( imp_4 )

long_data_4 <- complete( imp_4, action = "long", include = TRUE )
long_data_4$identity_change <- ifelse( long_data_4$sexual_identity_2014 == long_data_4$sexual_identity_2021, 0, 1 )
summary( long_data_4 )

fit_model_4 <- with( as.mids( long_data_4 ),
                     glm( identity_change ~ sexual_identity_2014, family = binomial( link = "log" ) ) )

pooled_summary_4 <- summary( pool( fit_model_4 ), conf.int = TRUE )
pooled_summary_4

model_4 <- tibble(
  "Estimate (log RR)" = round( pooled_summary_4[[ 2, "estimate" ]], 3 ), 
  "SE" = round( pooled_summary_4[[ 2, "std.error" ]], 3 ),
  "Lower CI" = round( pooled_summary_4[[ 2, "conf.low" ]], 3 ),
  "Upper CI" = round( pooled_summary_4[[ 2, "conf.high" ]], 3 ),
  
  "RR [95% CI]" = paste0(
    round( exp( pooled_summary_4[[ 2, "estimate" ]] ), 2 ), " [",
    round( exp( pooled_summary_4[[ 2, "conf.low" ]] ), 2 ), ", ",
    round( exp( pooled_summary_4[[ 2, "conf.high" ]] ), 2 ), "]" )
)
model_4[["Imputation Model"]] <- "Model 4: sexual identity, age, country of birth, antidepressant use, anxiolytic use"
model_4
```

##### 4.2.5. Model 5
```{r}
# additionally include age, country of birth, income, antidepressant use, and anxiolytic use

impute_data_5 <- d_2014_selected_male %>%
  select( sexual_identity_2014, sexual_identity_2021, age_2014, country_of_birth, income_2014, antidepressant_use_2014, anxiolytic_use_2014 )
summary( impute_data_5 )
str( impute_data_5 )
miss_var_summary( impute_data_5  )

imp_5 <- mice( impute_data_5, m = 50, seed = 123, print = FALSE )
summary( imp_5 )
plot( imp_5 )

long_data_5 <- complete( imp_5, action = "long", include = TRUE )
long_data_5$identity_change <- ifelse( long_data_5$sexual_identity_2014 == long_data_5$sexual_identity_2021, 0, 1 )
summary( long_data_5 )

fit_model_5 <- with( as.mids( long_data_5 ),
                     glm( identity_change ~ sexual_identity_2014, family = binomial( link = "log" ) ) )

pooled_summary_5 <- summary( pool( fit_model_5 ), conf.int = TRUE )
pooled_summary_5

model_5 <- tibble(
  "Estimate (log RR)" = round( pooled_summary_5[[ 2, "estimate" ]], 3 ), 
  "SE" = round( pooled_summary_5[[ 2, "std.error" ]], 3 ),
  "Lower CI" = round( pooled_summary_5[[ 2, "conf.low" ]], 3 ),
  "Upper CI" = round( pooled_summary_5[[ 2, "conf.high" ]], 3 ),
  
  "RR [95% CI]" = paste0(
    round( exp( pooled_summary_5[[ 2, "estimate" ]] ), 2 ), " [",
    round( exp( pooled_summary_5[[ 2, "conf.low" ]] ), 2 ), ", ",
    round( exp( pooled_summary_5[[ 2, "conf.high" ]] ), 2 ), "]" )
)
model_5[["Imputation Model"]] <- "Model 5: sexual identity, age, country of birth, income, antidepressant use, anxiolytic use"
model_5
```

##### 4.2.6. Print results
```{r}
bind_rows(
  model_cc, model_1, model_2, model_3, model_4, model_5
)
```