---
title: "DAG on Sexual Identity Change"
author: Willi Zhang, Maya Mathur, Ilya Shpitser
email: willi.zhang@ki.se
output: html_notebook
editor_options: 
  chunk_output_type: console
---

### 1. Load Packages
```{r}
library(ggdag)
library(ggplot2)
```

### 2. Sexual identities at T1 and T2
```{r}
theme_set( theme_dag() + theme( strip.text = element_blank() ) )

coords <- tibble::tribble(
  ~ name,                          ~ x,     ~ y,
  "sexual_identity_t1",            0.25,       0,
  "structural_stigma",             0.75,     0.5,
  "parental_leave",                0.75,     -0.5,
  "income",                        1.25,       0, 
  "sexual_identity_t2",            2,       0.25,
  "non_response",                  2,       -0.25,
  "sex",                           -0.25,    0
  )

set.seed( 123 )
sexual_identity_dag <- dagify(
  
  structural_stigma ~ sexual_identity_t1 + sex,
  parental_leave ~ sexual_identity_t1 + sex,
  sexual_identity_t2 ~ sexual_identity_t1 + structural_stigma,
  non_response ~ parental_leave,
  income ~ structural_stigma + parental_leave,

  exposure = "sexual_identity_t2",
  outcome = "non_response",
  latent = c( "structural_stigma", "parental_leave" ),
  
  labels = c(
    "sexual_identity_t2" = "Sexual identity\n(T2)",
    "sexual_identity_t1" = "Sexual identity\n(T1)",
    "non_response" = "Missingness of\nsexual identity\n(T2)",
    "income" = "Income",
    "structural_stigma" = "Structural stigmatization\nof sexual identity",
    "parental_leave" = "Parental leave",
    "sex" = "Sex"
    ),
  
  coords = coords
  
  )

p2 <- ggdag( sexual_identity_dag, 
             text = FALSE, 
             use_labels = "label"
             )
p2
ggsave( "dag_sexual_identity_change.jpeg", plot = p2, width = 10, height = 6.2, dpi = 600 )


ggdag_adjustment_set( sexual_identity_dag,
                      text = FALSE, 
                      use_labels = "label",
                      shadow = TRUE
                      )
```